Tipos de tensores

In [2]:
import torch

lista = [[1,2,3],
         [4,5,6],
         [7,8,9]]

tns = torch.LongTensor(lista)

print(tns.dtype)
print(tns)

torch.int64
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [3]:
import numpy as np
arr = np.random.randint(10,size=(3,4))
print(arr.dtype)

print(arr)
print(tns)

tns_numpy = torch.from_numpy(arr)

print(tns_numpy.dtype)
print(tns)

int32
[[3 7 6 7]
 [3 8 7 2]
 [4 7 1 0]]
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.int32
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [4]:
tns1 = torch.ones(3,3)
tns2 = torch.zeros(3,3)
tns3 = torch.randn(3,3)

print(tns1)
print(tns2)
print(tns3) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[ 1.1985,  0.7537, -0.0945],
        [ 2.0547,  0.1314,  0.5694],
        [-0.3413, -1.2772, -0.4347]])


In [5]:
arr = tns3.data.numpy()
print(arr.dtype)
arr

float32


array([[ 1.1985077 ,  0.7536979 , -0.09454452],
       [ 2.0547395 ,  0.13143353,  0.56941223],
       [-0.3412849 , -1.277202  , -0.43468687]], dtype=float32)

In [8]:
print(tns3)
tns3[1,2] = 77
print(tns3[0:2])

tensor([[ 1.1985,  0.7537, -0.0945],
        [ 2.0547,  0.1314, 77.0000],
        [-0.3413, -1.2772, -0.4347]])
tensor([[ 1.1985,  0.7537, -0.0945],
        [ 2.0547,  0.1314, 77.0000]])


Operações com vetores

In [22]:
tns = torch.randint(low=0,high=100,size=(3,3)) 
tns1 = torch.randint(low=0,high=100,size=(3,3))

print(f"{tns}\n")
print(f"{tns1}\n")
print(f"Soma {tns + tns1}\n")
print(f"Sub {tns - tns1}\n")
print(f"Multi {tns * tns1}\n")
print(f"Div {tns / tns1}\n")

tensor([[75, 13,  0],
        [ 8, 72, 32],
        [14, 56,  4]])

tensor([[24, 61, 94],
        [ 8,  5, 59],
        [75, 63, 38]])

Soma tensor([[ 99,  74,  94],
        [ 16,  77,  91],
        [ 89, 119,  42]])

Sub tensor([[ 51, -48, -94],
        [  0,  67, -27],
        [-61,  -7, -34]])

Multi tensor([[1800,  793,    0],
        [  64,  360, 1888],
        [1050, 3528,  152]])

Div tensor([[ 3.1250,  0.2131,  0.0000],
        [ 1.0000, 14.4000,  0.5424],
        [ 0.1867,  0.8889,  0.1053]])



In [33]:
print(tns1.size())
print(tns1.view(torch.float))

torch.Size([3, 3])
tensor([[3.3631e-44, 0.0000e+00, 8.5479e-44, 0.0000e+00, 1.3172e-43, 0.0000e+00],
        [1.1210e-44, 0.0000e+00, 7.0065e-45, 0.0000e+00, 8.2677e-44, 0.0000e+00],
        [1.0510e-43, 0.0000e+00, 8.8282e-44, 0.0000e+00, 5.3249e-44, 0.0000e+00]])


In [46]:
tns1 = tns1.view(-1)

tns1

tensor([24, 61, 94,  8,  5, 59, 75, 63, 38])

CAST NA GPU

In [49]:
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")
print(device)

cuda


In [51]:
tns = tns.to(device= device)
print(tns)

tensor([[75, 13,  0],
        [ 8, 72, 32],
        [14, 56,  4]], device='cuda:0')
