In [8]:
import torch
import numpy as np

# Tipos de Tensores

In [7]:
lista = [
    [1,2,3],
    [4,5,6]
]

print(type(lista))

tns = torch.Tensor(lista)
print(tns.dtype)
print(type(tns))

tns = torch.FloatTensor(lista)
print(tns.dtype)
print(type(tns))

tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(type(tns))

tns = torch.LongTensor(lista)
print(tns.dtype)
print(type(tns))

<class 'list'>
torch.float32
<class 'torch.Tensor'>
torch.float32
<class 'torch.Tensor'>
torch.float64
<class 'torch.Tensor'>
torch.int64
<class 'torch.Tensor'>


# Tensores a partir de arrays numpy

In [18]:
arr = np.random.rand(3,4) * 2
print(type(arr))
arr = arr.astype(int)
print(arr.dtype)

tns = torch.from_numpy(arr)
print(type(tns))
print(tns.dtype)

print(arr)
print(tns)

<class 'numpy.ndarray'>
int64
<class 'torch.Tensor'>
torch.int64
[[0 1 1 0]
 [0 0 0 1]
 [0 0 1 0]]
tensor([[0, 1, 1, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0]])


# Tensores inicializados

In [66]:
tns1 = torch.ones(2,2)
tns2 = torch.zeros(2,2)
tns3 = torch.rand(3,3)

print(tns1)
print(tns1.dtype)
print(tns2)
print(tns2.dtype)
print(tns3)
print(tns3.dtype)

tensor([[1., 1.],
        [1., 1.]])
torch.float32
tensor([[0., 0.],
        [0., 0.]])
torch.float32
tensor([[0.0346, 0.9771, 0.8530],
        [0.6843, 0.4224, 0.7693],
        [0.6986, 0.4711, 0.3842]])
torch.float32


In [67]:
arr = tns3.data.numpy()
print(arr)
print(arr.dtype)

[[0.03455573 0.97706366 0.85304236]
 [0.68428695 0.42239445 0.7692526 ]
 [0.69855344 0.47108376 0.38424736]]
float32


# Indexação

In [68]:
print(tns3)

print('')

tns3[0,1] = -10

print(tns3)

print('')

tns3[:,0] = 2

print(tns3)

tensor([[0.0346, 0.9771, 0.8530],
        [0.6843, 0.4224, 0.7693],
        [0.6986, 0.4711, 0.3842]])

tensor([[  0.0346, -10.0000,   0.8530],
        [  0.6843,   0.4224,   0.7693],
        [  0.6986,   0.4711,   0.3842]])

tensor([[  2.0000, -10.0000,   0.8530],
        [  2.0000,   0.4224,   0.7693],
        [  2.0000,   0.4711,   0.3842]])


# Operações com tensores

In [69]:
print(tns1)
print(tns3)

tns3 = tns3[:2,:2]

print(tns3)

tensor([[1., 1.],
        [1., 1.]])
tensor([[  2.0000, -10.0000,   0.8530],
        [  2.0000,   0.4224,   0.7693],
        [  2.0000,   0.4711,   0.3842]])
tensor([[  2.0000, -10.0000],
        [  2.0000,   0.4224]])


In [73]:
print(tns1 + tns3)
print('')
print(tns1 - tns3)
print('')
print(tns1 * tns3)
print('')
print(tns1 / tns3)
'''print('')
print(tns1 ^ tns3)
print('')
print(tns1 ** tns3)'''

tensor([[ 3.0000, -9.0000],
        [ 3.0000,  1.4224]])

tensor([[-1.0000, 11.0000],
        [-1.0000,  0.5776]])

tensor([[  2.0000, -10.0000],
        [  2.0000,   0.4224]])

tensor([[ 0.5000, -0.1000],
        [ 0.5000,  2.3675]])


"print('')\nprint(tns1 ^ tns3)\nprint('')\nprint(tns1 ** tns3)"

# .size , .view e .shape

In [91]:
tns = torch.randn(2,2,3)
print(tns)

print('')

print(tns.size())

print('')

print(tns.view(12))

print('')

print(tns.shape)

tensor([[[-2.4113, -1.9965, -1.0884],
         [ 0.0047,  0.2964,  0.9604]],

        [[ 0.4261, -0.6339, -0.1716],
         [ 0.5639,  0.1863,  0.5452]]])

torch.Size([2, 2, 3])

tensor([-2.4113, -1.9965, -1.0884,  0.0047,  0.2964,  0.9604,  0.4261, -0.6339,
        -0.1716,  0.5639,  0.1863,  0.5452])

torch.Size([2, 2, 3])


# GPU Cast

In [92]:
if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')
    
print(device)
    

cuda


In [93]:
tns = tns.to(device)
print(tns)

tensor([[[-2.4113, -1.9965, -1.0884],
         [ 0.0047,  0.2964,  0.9604]],

        [[ 0.4261, -0.6339, -0.1716],
         [ 0.5639,  0.1863,  0.5452]]], device='cuda:0')
